apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apikeymanager.fullname" . }}
  labels:
    {{- include "apikeymanager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "apikeymanager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "apikeymanager.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:          
            - name: "APIKM_ROOT_PATH"
              value: {{  .Values.config.root_path }}
            - name: "APIKM_DEBUG"
              value: {{  .Values.config.debug | quote }}
            - name: "APIKM_CORS_ORIGINS_REGEX"
              value: {{  .Values.config.cors_origins_regex | quote }}    
            - name: "APIKM_CORS_ALLOW_METHODS"
              value: {{  .Values.config.cors_allow_methods | quote }}
            - name: "APIKM_DATABASE_URL"
              valueFrom:
                secretKeyRef:
                  key:  database_url
                  name: {{ .Release.Name }}-auth
            - name: "APIKM_DEFAULT_APIKEY_TTL_HOUR"
              value: {{  .Values.config.default_apikey_ttl_hour | quote }}
            - name: "APIKM_OIDC_ENDPOINT"
              valueFrom:
                secretKeyRef:
                  key:  oidc_endpoint
                  name: {{ .Release.Name }}-auth
            - name: "APIKM_OIDC_REALM"
              valueFrom:
                secretKeyRef:
                  key:  oidc_realm
                  name: {{ .Release.Name }}-auth
            - name: "APIKM_OIDC_CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  key:  oidc_client_id
                  name: {{ .Release.Name }}-auth
            - name: "APIKM_OIDC_CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  key:  oidc_client_secret
                  name: {{ .Release.Name }}-auth
            - name: "APIKM_RATE_LIMIT"
              value: {{  .Values.config.rate_limit | quote }}
            - name: "APIKM_KEYCLOAK_SYNC_FREQ"
              value: {{  .Values.config.keycloak_sync_freq | quote }}
            - name: "APIKM_SHOW_TECHNICAL_ENDPOINTS"
              value: {{  .Values.config.show_technical_endpoints | quote }}
          {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/status
              port: http
          readinessProbe:
            httpGet:
              path: /health/status
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
