apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  allowed_origin_regex: {{ .Values.config.allowed_origin_regex | b64enc }}
  api_keys_db_url: {{ .Values.config.api_keys_db_url | b64enc }}
  oauth2_server_url: {{ .Values.config.oauth2_server_url | b64enc }}
  oauth2_realm: {{ .Values.config.oauth2_realm | b64enc }}
  oauth2_client_id: {{ .Values.config.oauth2_client_id | b64enc }}
  oauth2_client_secret: {{ .Values.config.oauth2_client_secret | b64enc }}
