apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  allowed_origin_regex: {{ .Values.config.allowed_origin_regex | b64enc }}
  api_keys_db_url: {{ .Values.config.api_keys_db_url | b64enc }}
  oidc_metadata_url: {{ .Values.config.oidc_metadata_url | b64enc }}
