# This file is part of APIKeyManger project
#     https://gitlab.si.c-s.fr/space_applications/apikeymanager/
# File generated by setuptools_scm
# don't change, don't track in version control
__version__ = "0.1.dev7+gac4e8ce.d20240506"
