# This file is part of APIKeyManger project
#     https://github.com/csgroup-oss/apikey-manager/
# File generated by setuptools_scm
# don't change, don't track in version control
__version__ = "0.1.dev11+g5226a24.d20240612"
