imagePullSecrets:
  - name: regcred

config:


ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: apikey.p2.csgroup.space
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: apikeymanager-tls
      hosts:
        - apikey.p2.csgroup.space
